---
title: Rise Up Pizza
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://riseuppizza.com
baseurl: "/Rise-Up"
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
plugins:
- jekyll-postcss
- jekyll-ical-tag
- jekyll-seo-tag
navigation:
  items:
  - title: Home
    url: "/"
  - title: Menu
    url: "/menu"
  - title: Schedule
    url: "/schedule"
  - title: Catering
    url: "/catering"
  - title: Weddings
    url: "/weddings"
sass:
  sourcemap: never
postcss:
  cache: false
exclude:
- ".gitignore"
- bin
- node_modules
- package-lock.json
- postcss.config.js
- README.md
keep_files:
- assets/css/tailwind.css
- assets/css/tailwind.css.map
